apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: add-task-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-add-task-api
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    path: /metrics
